spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sns?serverTimezone=Asia/Seoul
    username: root
    password: rootpassword
    #url: ${mysql.url}
    #    username: ${mysql.username}
    #    password: ${mysql.password}
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true

jwt:
  secret-key: project.sns-couple-application-2023-secret_key
  # 1 day
  expired-time-ms: 86400000
  # 30 days
  refresh-expired-time-ms: 2592000000

cloud:
  aws:
    credentials:
      access-key: AKIARCSPVP2JX6WCGXFZ
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: couple-sns-storage
    stack:
      auto: false